CREATE TABLE User(
id INTEGER PRIMARY KEY AUTO_INCREMENT ,
name VARCHAR(30) NOT NULL,
address VARCHAR(30) NOT NULL,
age INTEGER NOT NULL,
phone VARCHAR(10) NOT NULL,
email VARCHAR(30) NOT NULL,
password VARCHAR(30) NOT NULL,
status BOOLEAN default true,
role ENUM('user','admin'), 
created_at  DATETIME DEFAULT CURRENT_TIMESTAMP
 	
);